title: Gokhan Demir
url: http://yadazula.com
description: 'Personal site of Gokhan Demir'
keywords:
 - Gokhan Demir
 - yadazula

author:
    name: Gokhan Demir
    email: yadazula@gmail.com
    twitter: http://twitter.com/yadazula
    github: http://github.com/yadazula
    facebook: http://www.facebook.com/yadazula
    linkedin: http://www.linkedin.com/in/yadazula/
    avatar: http://www.gravatar.com/avatar/9d4b602fdbe05c0299cb8849045a4bd5?s=70
    openid:
        server: https://www.google.com/accounts/o8/ud
        delegate: http://www.google.com/profiles/yadazula
    
sections:
 - blog 
 - about
stylesheets:
 - /assets/themes/default/css/screen.css?52480=52480
 - /assets/themes/default/css/print.css
scripts:
 - http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js    
 - /assets/themes/default/js/jquery.tweet.js
 - /assets/themes/default/js/site.js
colors:
    highlights:
        blue: '#009ff7'
        green: '#87d14b'
        red: '#FF007C'
    mono:
        dark: '#000000'
        medium: '#777777'
        light: '#FFFFFF'
    bg: '#EAF1F4'
    
pygments: true
permalink: /blog/:year/:month/:day/:title 
exclude:
 - Rakefile
 - README.markdown
 - .git
